name: Build Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: false
          gradle-version: wrapper

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Docker image with Ktor
        run: ./gradlew publishImageToLocalRegistry

      - name: List Docker images
        run: docker images

      - name: Push Docker image
        run: docker push ghcr.io/stefanoltmann/emma-webapi:latest

      - name: Save Docker image as a tar archive
        run: |
          docker save -o emma-webapi-latest.tar ghcr.io/stefanoltmann/emma-webapi:latest

      - name: Upload Docker image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: emma-webapi-latest.tar
          path: emma-webapi-latest.tar
